# execution order
project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - about.qmd
    - 01_download_datasets_and_metadata.qmd
    - 02_02_preprocess_scRNASeq.qmd

# Website general layout
# see https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation to combine side bar and nav bar
website:
  title: "Reference profiles for Drosophila deconvolution"
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    title: "Navigation - Last Updated: {{< meta date >}}"
    style: "floating"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - about.qmd
      - section: "Download datasets"
        contents:
          - 01_download_datasets_and_metadata.qmd
      - section: "Preprocess purified transcriptomic samples"
        contents:
          - 02_01_preprocess_bulkRNASeq.qmd
          - 02_02_preprocess_scRNASeq.qmd
      - section: "Refine signature matrices"
      - section: "Apply deconvolution tools"
      - section: "Benchmark deconvolution tools"
      - section: "Biological applications on Drosophila ageing"

# Global metadata
author: "Bastien CHASSAGNOL and Savandara BESSE"
date: last-modified
bibliography: references.bib

# General format for eahc html page
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 2
    number-sections: true

